In [1]:
import numpy as np
import pandas as pd

In [2]:
# Need for DataFrame

np.random.seed(44)
arr = np.random.randint(0,100,(5,3))

print(arr)

[[20 35 45]
 [59  3 96]
 [84  3 23]
 [55 22 89]
 [67 71 67]]


In [6]:
print(type(arr))

<class 'numpy.ndarray'>


Creating a DataFrame from an Array

In [3]:
df = pd.DataFrame(arr)

In [4]:
df

0   1   2
0  20  35  45
1  59   3  96
2  84   3  23
3  55  22  89
4  67  71  67

In [5]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>


## Creating custom dataframe by defining rows & columns

In [7]:
rows = ['Mon','Tue','Wed','Thu','Fri']
cols = ['Jan','Feb','Mar']

In [8]:
df1 = pd.DataFrame(arr,index=rows,columns=cols)

In [9]:
df1

Jan  Feb  Mar
Mon   20   35   45
Tue   59    3   96
Wed   84    3   23
Thu   55   22   89
Fri   67   71   67

## Creating a DataFrame from Dictionary

In [10]:
mydict = {
            'Jan': [1,2,3,4,5],
            'Feb': [11,22,33,44,55],
            'Mar': [15,20,25,30,25]
        }

In [11]:
print(mydict)

{'Jan': [1, 2, 3, 4, 5], 'Feb': [11, 22, 33, 44, 55], 'Mar': [15, 20, 25, 30, 25]}


In [12]:
df2 = pd.DataFrame(mydict)

In [13]:
df2

Jan  Feb  Mar
0    1   11   15
1    2   22   20
2    3   33   25
3    4   44   30
4    5   55   25

In [17]:
df3 = pd.DataFrame(mydict, index = ['Mon','Tue','Wed','Thu','Fri'])
print(df3)

     Jan  Feb  Mar
Mon    1   11   15
Tue    2   22   20
Wed    3   33   25
Thu    4   44   30
Fri    5   55   25


### Since Dictonaries are unordered, we have too mention the order in which results need to be outputted

## Creating DatFrame from Files

In [20]:
#Syntax
df = pd.read_csv("sample_data.csv")

In [21]:
df

year industry_code_ANZSIC               industry_name_ANZSIC  \
0      2011                    A  Agriculture, Forestry and Fishing   
1      2011                    A  Agriculture, Forestry and Fishing   
2      2011                    A  Agriculture, Forestry and Fishing   
3      2011                    A  Agriculture, Forestry and Fishing   
4      2011                    A  Agriculture, Forestry and Fishing   
...     ...                  ...                                ...   
17023  2021                  all                     All Industries   
17024  2021                  all                     All Industries   
17025  2021                  all                     All Industries   
17026  2021                  all                     All Industries   
17027  2021                  all                     All Industries   

        rme_size_grp                                         variable  \
0                a_0                                    Activity unit   
1                a_0                           Rolling mean employees   
2                a_0                          Salaries and wages paid   
3                a_0  Sales, government funding, grants and subsidies   
4                a_0                                     Total income   
...              ...                                              ...   
17023  j_Grand_Total                                     Total income   
17024  j_Grand_Total                                Total expenditure   
17025  j_Grand_Total                      Operating profit before tax   
17026  j_Grand_Total                                     Total assets   
17027  j_Grand_Total                            Fixed tangible assets   

         value               unit  
0        46134              COUNT  
1            0              COUNT  
2          279  DOLLARS(millions)  
3         8187  DOLLARS(millions)  
4         8866  DOLLARS(millions)  
...        ...                ...  
17023   757504  DOLLARS(millions)  
17024   654404  DOLLARS(millions)  
17025    85116  DOLLARS(millions)  
17026  2512677  DOLLARS(millions)  
17027   591351  DOLLARS(millions)  

[17028 rows x 7 columns]

### Print Top 5/"n" rows

In [22]:
df.head(5)

year industry_code_ANZSIC               industry_name_ANZSIC rme_size_grp  \
0  2011                    A  Agriculture, Forestry and Fishing          a_0   
1  2011                    A  Agriculture, Forestry and Fishing          a_0   
2  2011                    A  Agriculture, Forestry and Fishing          a_0   
3  2011                    A  Agriculture, Forestry and Fishing          a_0   
4  2011                    A  Agriculture, Forestry and Fishing          a_0   

                                          variable  value               unit  
0                                    Activity unit  46134              COUNT  
1                           Rolling mean employees      0              COUNT  
2                          Salaries and wages paid    279  DOLLARS(millions)  
3  Sales, government funding, grants and subsidies   8187  DOLLARS(millions)  
4                                     Total income   8866  DOLLARS(millions)

### Print bottom 5/"n" rows

In [23]:
df.tail()

year industry_code_ANZSIC industry_name_ANZSIC   rme_size_grp  \
17023  2021                  all       All Industries  j_Grand_Total   
17024  2021                  all       All Industries  j_Grand_Total   
17025  2021                  all       All Industries  j_Grand_Total   
17026  2021                  all       All Industries  j_Grand_Total   
17027  2021                  all       All Industries  j_Grand_Total   

                          variable    value               unit  
17023                 Total income   757504  DOLLARS(millions)  
17024            Total expenditure   654404  DOLLARS(millions)  
17025  Operating profit before tax    85116  DOLLARS(millions)  
17026                 Total assets  2512677  DOLLARS(millions)  
17027        Fixed tangible assets   591351  DOLLARS(millions)

In [26]:
# Shape of the dataframe
df.shape

(17028, 7)

In [29]:
# to extract numpy array behind the dataframe
df.values

array([[2011, 'A', 'Agriculture, Forestry and Fishing', ...,
        'Activity unit', '46134', 'COUNT'],
       [2011, 'A', 'Agriculture, Forestry and Fishing', ...,
        'Rolling mean employees', '0', 'COUNT'],
       [2011, 'A', 'Agriculture, Forestry and Fishing', ...,
        'Salaries and wages paid', '279', 'DOLLARS(millions)'],
       ...,
       [2021, 'all', 'All Industries', ...,
        'Operating profit before tax', '85116', 'DOLLARS(millions)'],
       [2021, 'all', 'All Industries', ..., 'Total assets', '2512677',
        'DOLLARS(millions)'],
       [2021, 'all', 'All Industries', ..., 'Fixed tangible assets',
        '591351', 'DOLLARS(millions)']], dtype=object)

In [37]:
index = [1, 2, 3, 4, 5]
col1 = list('abcde')
col2 = list('pqrst')

# Correcting the columns parameter
df_q1 = pd.DataFrame(index=index, columns=[list(col1),list(col2)])

In [38]:
df_q1

a    b    c    d    e
     p    q    r    s    t
1  NaN  NaN  NaN  NaN  NaN
2  NaN  NaN  NaN  NaN  NaN
3  NaN  NaN  NaN  NaN  NaN
4  NaN  NaN  NaN  NaN  NaN
5  NaN  NaN  NaN  NaN  NaN

## Pandas Series

Pandas Series is a type that is used to store one column only.
We can think of series as one column of a dataframe extracted.

series is very similar to numpy array, with the major difference being it has an index label for each observation.

In [35]:
df4 = pd.DataFrame(np.random.randint(1,100,(5,4)),columns=list('abcd'))

In [36]:
df4

a   b   c   d
0  58   2  15  37
1  94  86  84  97
2  75  37  32  19
3  73  94  62  73
4  75  87  17  73

In [40]:
df4['a']

0    58
1    94
2    75
3    73
4    75
Name: a, dtype: int64

In [41]:
print(type(df4['a']))

<class 'pandas.core.series.Series'>


In [42]:
# Slicing from pandas series
df4['a'][2]

75

In [43]:
# Creating a list from the slicing elemnets from the series
df4['a'][:4].tolist()

[58, 94, 75, 73]

## Creating a Standalone Series Object

In [51]:
data = np.arange(10)
index = ['a','b','c','d','e','f','g','h','i','j']

ser = pd.Series(data=data,index=index)

In [52]:
ser

a    0
b    1
c    2
d    3
e    4
f    5
g    6
h    7
i    8
j    9
dtype: int64

In [53]:
print(type(ser))

<class 'pandas.core.series.Series'>


In [54]:
# Series are Vectorized Objects by default.
# In order to print squares of every item in series, we need to iterate through loop
# Insted directly perform squaring operation

squares = ser ** 2

print(squares)

a     0
b     1
c     4
d     9
e    16
f    25
g    36
h    49
i    64
j    81
dtype: int64


In [56]:
# Extract Indiviual items from series

ser['g']

6

In [58]:
# To extract more than one item, put all the item labels in a list and then pass it as an arument

ser[['d','i','c']]

d    3
i    8
c    2
dtype: int64

## Creating Pandas Series from Dictionary

In [59]:
d1 = {'a':1,'b':2,'c':6}
d2 = {'d':8,'f':15,'h':11}

ser1 = pd.Series(d1)
ser2 = pd.Series(d2)

In [62]:
print(ser1)
print(ser2)

a    1
b    2
c    6
dtype: int64
d     8
f    15
h    11
dtype: int64


In [67]:
# Adding thesee two series objects

s = ser1.values + ser2.values

In [68]:
s

array([ 9, 17, 17])